import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TanstackProvider from "@/components/providers/tan-stack-provider";
import { AuthProvider } from "@/context/authContext";
import { ToastProvider } from "@/context/ToastContext";
import { Toaster, toast } from 'sonner'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Point AI",
  icons: "/public/logo.png",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/src/app/logo.ico" />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <TanstackProvider>
            <ToastProvider>
              <Toaster richColors expand={false} />
              {children}
            </ToastProvider>
          </TanstackProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
